### ISSUE TITLE
Generic Data Service

### ISSUE THREAD

**Issue by lharzenetter** [UST-QuAntiL/qc-atlas-ui#125]
Why we have this additional service? Couldn't this be replaced with the genereated ones?

Benefits
- Returened data is typed, i.e., Intellisense is available and compile-time errors
- Clearer structure

**Comment by salmma** [comment]
see src/app/util/generic-data.service.ts

**Comment by ValeSayfa** [comment]
This generic service will be used to fetch data using the hal links (e.g. for pagination).

**Comment by salmma** [comment]
Done with #136
