### ISSUE TITLE
Sort List of Problem Types by Parent Problem Type Name (+ Code Improvement)

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/qc-atlas-ui#134]
Currently, sorting the list of problem types under "Manage Components" does not work as the request 
`GET http://localhost:8080/atlas/problem-types?page=0&size=10&sort=parentProblemTypeName,asc`
to the QC Atlas returns a 500 because sorting by parent problem type **NAME** is not supported.
If necessary I would propose to hide the sorting possibility at the "Parent" column.

Further, if possible, improve the logic of the `assignParentProblemTypeNames()` method to reduce the number of requests for each problem type with a parent problem type. 
**But be careful that also pagination is supported with more than one page!**
That is why I adapted the original method: 
In case the parent problem type was on another page, the problem type did not show a parent.

**Comment by emymaria** [comment]
It seems like the issue was at backend, so I added sort based on parent at backend. But since this bug is raised at frontend, I could not find a way to raise my PR. Please help.
Also I found that the sort direction is asc, desc and unsort. Do we actually need all 3 or should I get rid of the unsort state

**Comment by salmma** [comment]
Just make a PR if you finished the backend and link to the frontend PR and vice versa - in case changes at frontend side are required. Otherwise write a comment here with a link to the backend PR. 
I think unsort for the parents is required otherwise a sorting on problemTypes (first column) is difficult?

**Comment by emymaria** [comment]
I raised the PR. https://github.com/UST-QuAntiL/qc-atlas/pull/195. But could not figure out how to link it to here.
