### ISSUE TITLE
Reordering of Algorithm Properties in Algorithm Overview

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/qc-atlas-ui#152]
Based on the detailed platform content, the properties fields in the Algorithm Overview should be reordered and maybe enlarged dependent on the general text length of the single fields.

Also have a look at publications and implementations, etc.

Here is a sketch of the re-ordered structure for algorithm properties:

<img width="793" alt="Bildschirmfoto 2021-08-04 um 10 40 45" src="https://user-images.githubusercontent.com/23473511/128161176-d089f85a-fc4e-4b76-8421-9e6e1e0d1ec0.png">

Relates to https://github.com/UST-QuAntiL/latex-renderer/issues/9

**Comment by mbeisel** [comment]
In general it might be a good idea to move away from the 3 column layout and just have one or a maximum of two columns. This generally improves the user experience at difference browser window sizes and leaves more space for content and pictures (especially related to Latex-Rendering https://github.com/UST-QuAntiL/qc-atlas-ui/pull/155 ). When done scrollboxes, max-width/height values etc. must be adjusted accordingly.
