### ISSUE TITLE
NISQ Analyzer: Compiler Comparison - automated refresh

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/qc-atlas-ui#187]
Under the Execution tab of an implementation: enable an automated refresh of the table as soon as the compiler-selection results are available when adding a new compilation and after clicking the execute button.
Thus, the Refresh button is obsolete and can be removed.

**Comment by emymaria** [comment]
https://user-images.githubusercontent.com/68675647/156921874-20c60a54-9908-4a5c-8dd7-3fb6d7cd6147.mp4
