### ISSUE TITLE
NISQ Analyzer: Remove "Width rule" & "Depth rule"input fields for PROLOG rules (size: small)

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/qc-atlas-ui#77]
Please remove the "Width rule" & "Depth rule" under Implementation Selection Criteria sch thtat for PROLOG rules only the Selection rule is shown.

###Acceptance Criteria:
1. Do not show input fields for "Width rule" & "Depth rule"

**Comment by timniederhausen** [comment]
see #85
