### ISSUE TITLE
Prevent scrollbar on text fields

### ISSUE THREAD

**Issue by FlxB2** [UST-QuAntiL/qc-atlas-ui#82]
If too much text is added to a text field a scrollbar appears which looks weird and is obstructive for users, especially when inserting longer texts. This can be fixed by automatically adding more height to the text field.

![screen](https://user-images.githubusercontent.com/7521847/94668460-5bd55600-0310-11eb-8516-c84ff48a1db8.png)

**Comment by LHommeDeBat** [comment]
Will be fixed inPR: https://github.com/UST-QuAntiL/qc-atlas-ui/pull/109
