### ISSUE TITLE
NISQ Analyzer: provided sdks

### ISSUE THREAD

**Issue by FlxB2** [UST-QuAntiL/qc-atlas-ui#94]
Currently the ui expects the Qiskit SDK to be contained inside the nisq analyzer db. 
This causes several issues when using an empty db, as mentioned in this [pull request](https://github.com/UST-QuAntiL/quantil-docker/pull/2)

**Comment by timniederhausen** [comment]
This is already part of this issue: https://github.com/UST-QuAntiL/qc-atlas-ui/issues/81
